---
- name: Download WP-CLI
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/tmp/wp-cli.phar

- name: Add WP-CLI to bin
  command: mv /tmp/wp-cli.phar /usr/local/bin/wp creates=/usr/local/bin/wp

- name: Make WP-CLI executable
  file: path=/usr/local/bin/wp owner=root group=root mode=770

- name: Download WordPress
  command: wp core download
  args:
      chdir: "/var/www/html/"

- name: Set file permissions
  file: dest=/var/www/html/ owner=root group=apache mode=u=rwX,g=rX,o=rX recurse=yes
  
- name: Configure WordPress
  command: wp core config
           --path="/var/www/html"
           --dbhost='{{ wordpress_db_host}}' 
           --dbname="{{ wordpress_db_name }}"
           --dbuser="{{ wordpress_db_user }}"
           --dbpass="{{ wordpress_db_pass }}"

- name: Get public DNS name of the EC2 instance
  uri: url="http://169.254.169.254/latest/meta-data/public-hostname" return_content=yes
  register: public_hostname

- name: Install WordPress
  command: wp core install
            --url="{{ public_hostname.content }}"
            --title="{{ wordpress_site_title }}"
            --admin_user="{{ wordpress_admin_user }}"
            --admin_password="{{ wordpress_admin_pass }}"
            --admin_email="{{ wordpress_admin_email }}"
  args:
      chdir: "/var/www/html/"
      
- name: Print WordPress website URL
  debug:
    msg: "WordPress website URL:  http://{{ public_hostname.content }}"
